version: '3.8'

services:
  dacxi-app:
    env_file:
      - .env
    container_name: dacxi-app
    restart: unless-stopped
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - dacxi-postgres
    environment:
      - PHP_MEMORY_LIMIT=512M
      - PHP_MAX_EXECUTION_TIME=120
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - dacxi

  dacxi-postgres:
    image: postgres:12.0-alpine
    container_name: dacxi-postgres
    restart: unless-stopped
    tty: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dacxi_cb
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - "./.data/dbdata:/var/lib/postgresql/data"
    networks:
      - dacxi

  dacxi-nginx:
    image: nginx:alpine
    container_name: dacxi-nginx
    restart: always
    ports:
      - "9000:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - dacxi-app
    networks:
      - dacxi

volumes:
  pgsql:
    driver: local

networks:
  dacxi:
    driver: bridge
