version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dacxi_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - dacxi_network
    depends_on:
      - mysql
    environment:
      - PHP_MEMORY_LIMIT=512M
      - PHP_MAX_EXECUTION_TIME=120

  mysql:
    image: mysql:5.7
    container_name: dacxi_mysql
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: dacxi_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dacxi_network

  webserver:
    image: nginx:alpine
    container_name: dacxi_web
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dacxi_network

volumes:
  mysql_data:

networks:
  dacxi_network:
    driver: bridge
